### ISSUE TITLE
Investigar framework multiidioma

### ISSUE THREAD

**Issue by adrianq** [adrianq/msf_apps#4]

**Comment by HelderCastrillon** [comment]
@josemp10 @adrianq  ustedes pueden ver la posibilidad de identificar el idioma configurado en el usuario de dhis , en la api vi que aparece los idiomas del usuario  en el recurso api/me?fields=languages, quizá se pueda consultar cual es que esta configurado por defecto para el usuario.

esto estuvo en las solicitudes de MSF

:)

**Comment by adrianq** [comment]
@HelderCastrillon ok, nosotros lo miramos
